export const commerceCopy = {
  fr: {
    product: "Produit",
    category: "Categorie",
    price: "Prix",
    inventory: "Inventaire",
    status: "Statut",
    total: "Total",
    customer: "Client",
    view: "Voir",
    demoCheckout: "Checkout demo",
    addToCart: "Ajouter au panier demo",
    products: "Produits",
    orders: "Commandes",
    dashboard: "Operations",
    caseStudy: "Etude de cas",
  },
  en: {
    product: "Product",
    category: "Category",
    price: "Price",
    inventory: "Inventory",
    status: "Status",
    total: "Total",
    customer: "Customer",
    view: "View",
    demoCheckout: "Demo checkout",
    addToCart: "Add to demo cart",
    products: "Products",
    orders: "Orders",
    dashboard: "Operations",
    caseStudy: "Case study",
  },
};
